### ISSUE TITLE
Relicensing to Apache 2 License

### ISSUE THREAD

**Issue by olifre** [olifre/dockerhub2oci#3]
The proposal has been raised in Charliecloud ( https://github.com/hpc/charliecloud/issues/41#issuecomment-367766108 ) to make the code of this project readable to developers which are working with a less restrictive license than GPL 3. 

Apache 2.0 was proposed. It's notably not a copyleft license. 
Compatibility with the currently used GPL 3 is possible:
https://en.wikipedia.org/wiki/Apache_License#GPL_compatibility
i.e. Apache 2.0 code can be used in a GPL 3 software, but not the other way around. 

To relicense, all contributors have to accept this proposal. 
It should be legally sufficient if you reply to this post with:
```
I agree that my past contributions to dockerhub2oci are relicensed to 
the Apache license, version 2.0. 
```

Since there is only one contributor right now, pinging @DrDaveD on his opinion - in case you accept, just reply with the block of text shown above. Thanks!

**Comment by DrDaveD** [comment]
I'm sorry for the delay, I'm way behind in email.

I agree that my past contributions to dockerhub2oci are relicensed to 
the Apache license, version 2.0.

**Comment by olifre** [comment]
> I'm sorry for the delay, I'm way behind in email.

No problem - going ahead now to convince GitHub to change the license.
