### ISSUE TITLE
registry as variable

### ISSUE THREAD

**Issue by vsoch** [olifre/dockerhub2oci#4]
hey @olifre ! I'm making a small web interface to manage images, and am running into this (extremely old by now!) issue of whiteout files. I just gave dockerhub2oci a go and I think this will do the trick - is there any reason we are limited to using Docker Hub as the registry endpoint, as opposed to allowing it to also be specified as a variable? For example, I'd like to be able to use it for nvidia images on the GPU cloud (they also have the whiteout files). Looking forward to chatting about this!

**Comment by vsoch** [comment]
oh, and I really like the green, it looks really nice on my purple terminal :)

![image](https://user-images.githubusercontent.com/814322/37873060-9ac7a3e4-2fe2-11e8-9270-14beadbe3363.png)
b

**Comment by olifre** [comment]
Hi @vsoch !
Yes, indeed, there was no real reason `registry` was not a parameter yet. I added it just now. 
My main problem was I don't have a custom registry to test with - could you test whether it works as expected now? 

For the nice green colour, credits go to:
https://aria2.github.io/
All the nice downloading features come from aria2c :wink:

**Comment by olifre** [comment]
> nvidia images on the GPU cloud

Is this public? Then I could use it for testing :smile:

**Comment by vsoch** [comment]
oops, I was writing a message to you as you posted, and am just seeing this! Take a look at the PR and let me know if you think the blob2oci is useful, I'm thinking that your implementation of adding the registry is likely better. 

It is extremely hard to test, actually, because nvidia GPU cloud is not public, it requires a special username of "$oauth_token" (and yes I would bet you many evaluate the environment variable and miss that) and then a token. For this reason I decided it would make more sense to let the user handle the https part, and just focus on the harder thing that is handling the whiteout. Let me know what you think is best to do to proceed.
